### ISSUE TITLE
修改别人源代码？

### ISSUE THREAD

**Issue by WeiHea** [MistEO/B-K#1]
https://github.com/aya015757881/brainfuck_interpreter.git

**Comment by MistEO** [comment]
缓缓打出一个问号

**Comment by WeiHea** [comment]
> 缓缓打出一个问号

抱歉，之前看了一个几乎一样项目，没注意看你项目的介绍，不好意思。

**Comment by hewei-nju** [comment]
> 缓缓打出一个问号

抱歉，之前看了一个几乎一样项目，没注意看你项目的介绍，不好意思。

**Comment by MistEO** [comment]
[BrainFuck](https://zh.wikipedia.org/wiki/Brainfuck) 是一门小众的编程语言，谁都可以自己写一个 BrainFuck 解释器的

不过我这个其实是为了[参赛](https://github.com/InvoluteHell/HelloWorldContest)，钻空子临时写的（

**Comment by WeiHea** [comment]
嗯嗯，我刚去搜了下，是的！感谢科普。
非常抱歉，打扰了，非常冒昧的去评论了，不好意思。

--------------原始邮件--------------
发件人："MistEO ***@***.***&gt;;
发送时间：2021年12月18日(星期六) 晚上9:39
收件人："MistEO/B-K" ***@***.***&gt;;
抄送："贺伟 ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [MistEO/B-K] 修改别人源代码？ (Issue #1)
-----------------------------------

 

 
BrainFuck 是一门小众的编程语言，谁都可以自己写一个 BrainFuck 解释器的
 
不过我这个其实是为了参赛，钻空子临时写的（
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
